from django.db import models

# Create your models here.

class Client(models.Model):
	ClientID = models.TextField(unique = True)
	ClientName = models.TextField(null = True)
	CreatedOn = models.DateField(null = True)
	ShortName = models.TextField(unique = True)


class StagingRecords(models.Model):
	sr_no = models.IntegerField(unique = True)
	recruiter = models.ForeignKey('user.User', on_delete = models.DO_NOTHING)
	client = models.ForeignKey('Client', on_delete = models.DO_NOTHING)
	position = models.TextField(null = True)
	reqt_date = models.DateField(null = True)
	date_cv_submitted = models.DateField(null = True)
	candidate_name = models.TextField(null = True)
	current_status = models.IntegerField(null = True)
	current_status_desc = models.TextField(null = True)
	interview_date = models.DateField(blank = True)
	remarks = models.TextField(blank = True)
	skills = models.TextField(null = True)
	current_org = models.TextField(null = True)
	qualification = models.TextField(null = True)
	total_exp = models.FloatField(null = True)
	current_location = models.TextField(null = True)
	contact_details_mobile = models.IntegerField(max_length = 10)
	contact_details_phone2 = models.IntegerField(max_length = 10)
	email = models.EmailField(null = True)
	current_salary = models.FloatField(null = True)
	expected_salary_percentage = models.IntegerField(null = True)
	expected_salary_amt = models.FloatField(null = True)
	notice_period = models.FloatField(null = True)
	Int_Tele_Date = models.DateField(blank = True)
	Int_Tele_Result = models.TextField(blank = True)
	Int_P1_Date = models.DateField(blank = True)
	Int_P1_Result = models.TextField(blank = True)
	Int_p2_Date = models.DateField(blank = True)
	Int_p2_Result = models.TextField(blank = True)
	Int_p3_Date = models.DateField(blank = True)
	Int_p3_Result = models.TextField(blank = True)
	Int_Final_Date = models.DateField(blank = True)
	Int_Final_Result = models.TextField(blank = True)
	Int_HR_Date = models.DateField(blank = True)
	Int_HR_Result = models.TextField(blank = True)
	offer_date = models.DateField(blank = True)
	offer_amt = models.FloatField(blank = True)
	joining_date = models.DateField(blank = True)
	vacancy_code = models.TextField(blank = True)
	applicant_code = models.TextField(blank = True)
	DOB = models.DateField(blank = True)
	preferred_company = models.TextField(blank = True)
	preferred_location = models.TextField(blank = True)
	week_number = models.IntegerField(blank = True)
	wk_year = models.IntegerField(blank = True)

class GoodRecords(models.Model):
	sr_no = models.IntegerField(unique = True)
	recruiter = models.ForeignKey('user.User', on_delete = models.DO_NOTHING)
	client = models.ForeignKey('Client', on_delete = models.DO_NOTHING)
	position = models.TextField(null = True)
	reqt_date = models.DateField(null = True)
	date_cv_submitted = models.DateField(null = True)
	candidate_name = models.TextField(null = True)
	current_status = models.IntegerField(null = True)
	current_status_desc = models.TextField(null = True)
	interview_date = models.DateField(blank = True)
	remarks = models.TextField(blank = True)
	skills = models.TextField(null = True)
	current_org = models.TextField(null = True)
	qualification = models.TextField(null = True)
	total_exp = models.FloatField(null = True)
	current_location = models.TextField(null = True)
	contact_details_mobile = models.IntegerField(max_length = 10)
	contact_details_phone2 = models.IntegerField(max_length = 10)
	email = models.EmailField(null = True)
	current_salary = models.DecimalField(null = True)
	sr_no = models.IntegerField(unique = True)
	recruiter = models.ForeignKey('user.User', on_delete = models.DO_NOTHING)
	client = models.ForeignKey('Client', on_delete = models.DO_NOTHING)
	position = models.TextField(null = True)
	reqt_date = models.DateField(null = True)
	date_cv_submitted = models.DateField(null = True)
	candidate_name = models.TextField(null = True)
	current_status = models.IntegerField(null = True)
	current_status_desc = models.TextField(null = True)
	interview_date = models.DateField(blank = True)
	remarks = models.TextField(blank = True)
	skills = models.TextField(null = True)
	current_org = models.TextField(null = True)
	qualification = models.TextField(null = True)
	total_exp = models.FloatField(null = True)
	current_location = models.TextField(null = True)
	contact_details_mobile = models.IntegerField( )
	contact_details_phone2 = models.IntegerField( )
	email = models.EmailField(null = True)
	current_salary = models.FloatField(null = True)
	expected_salary_percentage = models.IntegerField(null = True)
	expected_salary_amt = models.FloatField(null = True)
	notice_period = models.FloatField(null = True)
	Int_Tele_Date = models.DateField(blank = True)
	Int_Tele_Result = models.TextField(blank = True)
	Int_P1_Date = models.DateField(blank = True)
	Int_P1_Result = models.TextField(blank = True)
	Int_p2_Date = models.DateField(blank = True)
	Int_p2_Result = models.TextField(blank = True)
	Int_p3_Date = models.DateField(blank = True)
	Int_p3_Result = models.TextField(blank = True)
	Int_Final_Date = models.DateField(blank = True)
	Int_Final_Result = models.TextField(blank = True)
	Int_HR_Date = models.DateField(blank = True)
	Int_HR_Result = models.TextField(blank = True)
	offer_date = models.DateField(blank = True)
	offer_amt = models.FloatField(blank = True)
	joining_date = models.DateField(blank = True)
	vacancy_code = models.TextField(blank = True)
	applicant_code = models.TextField(blank = True)
	DOB = models.DateField(blank = True)
	preferred_company = models.TextField(blank = True)
	preferred_location = models.TextField(blank = True)
	week_number = models.IntegerField(blank = True)
	wk_year = models.IntegerField(blank = True)


class BadRecords(models.Model):
	sr_no = models.IntegerField(unique = True)
	recruiter = models.ForeignKey('user.User', on_delete = models.DO_NOTHING)
	client = models.ForeignKey('Client', on_delete = models.DO_NOTHING)
	position = models.TextField(null = True)
	reqt_date = models.DateField(null = True)
	date_cv_submitted = models.DateField(null = True)
	candidate_name = models.TextField(null = True)
	current_status = models.IntegerField(null = True)
	current_status_desc = models.TextField(null = True)
	interview_date = models.DateField(blank = True)
	remarks = models.TextField(blank = True)
	skills = models.TextField(null = True)
	current_org = models.TextField(null = True)
	qualification = models.TextField(null = True)
	total_exp = models.FloatField(null = True)
	current_location = models.TextField(null = True)
	contact_details_mobile = models.IntegerField(max_length = 10)
	contact_details_phone2 = models.IntegerField(max_length = 10)
	email = models.EmailField(null = True)
	current_salary = models.DecimalField(null = True)
	sr_no = models.IntegerField(unique = True)
	recruiter = models.ForeignKey('user.User', on_delete = models.DO_NOTHING)
	client = models.ForeignKey('Client', on_delete = models.DO_NOTHING)
	position = models.TextField(null = True)
	reqt_date = models.DateField(null = True)
	date_cv_submitted = models.DateField(null = True)
	candidate_name = models.TextField(null = True)
	current_status = models.IntegerField(null = True)
	current_status_desc = models.TextField(null = True)
	interview_date = models.DateField(blank = True)
	remarks = models.TextField(blank = True)
	skills = models.TextField(null = True)
	current_org = models.TextField(null = True)
	qualification = models.TextField(null = True)
	total_exp = models.FloatField(null = True)
	current_location = models.TextField(null = True)
	contact_details_mobile = models.IntegerField( )
	contact_details_phone2 = models.IntegerField( )
	email = models.EmailField(null = True)
	current_salary = models.FloatField(null = True)
	expected_salary_percentage = models.IntegerField(null = True)
	expected_salary_amt = models.FloatField(null = True)
	notice_period = models.FloatField(null = True)
	Int_Tele_Date = models.DateField(blank = True)
	Int_Tele_Result = models.TextField(blank = True)
	Int_P1_Date = models.DateField(blank = True)
	Int_P1_Result = models.TextField(blank = True)
	Int_p2_Date = models.DateField(blank = True)
	Int_p2_Result = models.TextField(blank = True)
	Int_p3_Date = models.DateField(blank = True)
	Int_p3_Result = models.TextField(blank = True)
	Int_Final_Date = models.DateField(blank = True)
	Int_Final_Result = models.TextField(blank = True)
	Int_HR_Date = models.DateField(blank = True)
	Int_HR_Result = models.TextField(blank = True)
	offer_date = models.DateField(blank = True)
	offer_amt = models.FloatField(blank = True)
	joining_date = models.DateField(blank = True)
	vacancy_code = models.TextField(blank = True)
	applicant_code = models.TextField(blank = True)
	DOB = models.DateField(blank = True)
	preferred_company = models.TextField(blank = True)
	preferred_location = models.TextField(blank = True)
	week_number = models.IntegerField(blank = True)
	wk_year = models.IntegerField(blank = True)
	reason = models.TextField(blank = True)
