# Generated by Django 3.1 on 2020-08-18 16:44

from django.db import migrations, models
# from django.contrib.postgres.operations import HStoreExtension

class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        # HStoreExtension(),
        migrations.CreateModel(
            name='Mapped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Excel', models.TextField(blank=True, null=True)),
                ('Db', models.CharField(max_length=30)),
            ],
        ),
    ]
