# Generated by Django 3.1 on 2020-08-18 16:48

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_mapped'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mapped',
        ),
        migrations.AddField(
            model_name='mapping',
            name='Mappings',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
