# Generated by Django 3.1 on 2020-08-18 17:09

from django.db import migrations
from django.contrib.postgres.operations import (HStoreExtension)


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_auto_20200818_2218'),
    ]

    operations = [
        HStoreExtension()
    ]
