# Generated by Django 3.0.8 on 2020-08-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('organisation_type', models.CharField(max_length=10)),
                ('organisation_name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('pin_code', models.CharField(default='143001', max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('password', models.CharField(default=None, max_length=50)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
    ]
