# Generated by Django 3.1 on 2020-08-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='valid',
        ),
        migrations.AddField(
            model_name='user',
            name='CreatedOn',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Department',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Designation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='EmailID',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='FullName',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='UserCompany',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='UserDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='UserReportsTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='UserStatus',
            field=models.TextField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='UserType',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ValidTill',
            field=models.DateField(null=True),
        ),
    ]
